CREATE TABLE IF NOT EXISTS Usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    nick TEXT NOT NULL UNIQUE,
    video TEXT
);

CREATE TABLE IF NOT EXISTS Amistad (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_usu1 INTEGER NOT NULL,
    id_usu2 INTEGER NOT NULL,
    FOREIGN KEY(id_usu1) REFERENCES Usuario(id) ON DELETE CASCADE,
    FOREIGN KEY(id_usu2) REFERENCES Usuario(id) ON DELETE CASCADE,
    UNIQUE(id_usu1, id_usu2)
);

PRAGMA foreign_keys = ON;