version: '3'
services:
  api:
    build: ./API
    command: ["./wait-for-it.sh", "-t", "25", "rabbitmq:5672", "--", "npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  transcodificador:
    build: ./Transcodificador
    command: ["./wait-for-it.sh", "-t", "25", "rabbitmq:5672", "--", "node", "transcoder.js"]
    volumes:
      - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  rabbitmq:
    build: ./RabbitMQ
    ports:
    - "15673:15672"
    networks:
      - oneTakeNetwork

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OneTake
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - oneTakeNetwork
    volumes:
      - ./Scripts/script.sql:/docker-entrypoint-initdb.d/script.sql

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

networks:
  oneTakeNetwork:

volumes:
  almacenamientoVideos: