version: '3'
services:
  api:
    build: ./API
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]
    #command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
    - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  transcoder:
    build: ./Transcodificador
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "node", "transcoder.js"]
    volumes:
      - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  rabbitmq:
    build: ./RabbitMQ
    ports:
    - "15673:15672"
    networks:
      - oneTakeNetwork

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OneTake
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - oneTakeNetwork
    volumes:
      - ./API/sql-scripts/script.sql:/docker-entrypoint-initdb.d/script.sql

networks:
  oneTakeNetwork:

volumes:
  almacenamientoVideos: