version: '3'
services:
  api:
    build: ./API
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]
    ports:
      - "3000:3000"
    volumes:
    - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  transcoder:
    build: ./Transcodificador
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "node", "transcoder.js"]
    volumes:
      - almacenamientoVideos:/mnt/volumen
    networks:
      - oneTakeNetwork

  rabbitmq:
    build: ./RabbitMQ
    ports:
    - "15673:15672"
    networks:
      - oneTakeNetwork

networks:
  oneTakeNetwork:

volumes:
  almacenamientoVideos: