CREATE DATABASE IF NOT EXISTS OneTake;
USE OneTake;

CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    nick VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE PETICION_AMISTAD (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_enviador INT NOT NULL,
    id_receptor INT NOT NULL,
    FOREIGN KEY (id_enviador) REFERENCES USUARIO(id),
    FOREIGN KEY (id_receptor) REFERENCES USUARIO(id)
);

CREATE TABLE RELACION_AMISTAD (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_usuario1 INT NOT NULL,
    id_usuario2 INT NOT NULL,
    FOREIGN KEY (id_usuario1) REFERENCES USUARIO(id),
    FOREIGN KEY (id_usuario2) REFERENCES USUARIO(id)
);